package main

import (
	"flag"
	"fmt"
	"log"
	"os"
)

func exists(name string) bool {
	_, err := os.Stat(name)
	return err == nil
}

func main() {
	var (
		rockstarDir, treeDir, memoDir, gtetFmt string
	)

	flag.StringVar(&rockstarDir, "RockstarDir", "",
		"Directory containing Rockstar halo files.")
	flag.StringVar(&treeDir, "TreeDir", "",
		"Directory containing merger trees generated by consistent trees.")
	flag.StringVar(&memoDir, "MemoDir", "",
		"Directory where memoization will be performed.")
	flag.StringVar(&gtetFmt, "GtetFmt", "",
		"A format string that gives the directory containing .gtet files. " +
			"Accepts one int.")

	flag.Parse()

	if !exists(rockstarDir) {
		log.Fatalf("Directory %s does not exist.", rockstarDir)
	} else if !exists(treeDir) {
		log.Fatalf("Directory %s does not exist.", treeDir)
	} else if !exists(fmt.Sprintf(gtetFmt, 0)) {
		log.Fatalf("Directory %s does not exist.", fmt.Sprintf(gtetFmt, 0))
	}

	if !exists(memoDir) {
		err := os.MkdirAll(memoDir, os.ModeDir)
		if err != nil { log.Fatal(err.Error()) }
	}

	os.Setenv("GTET_ROCKSTAR_DIR", rockstarDir)
	os.Setenv("GTET_TREE_DIR", treeDir)
	os.Setenv("GTET_MEMO_DIR", memoDir)
	os.Setenv("GTET_FMT", gtetFmt)
}
