package main

import (
	"flag"
	"log"
	"os"
)

func exists(name string) bool {
	_, err := os.Stat(name)
	return err == nil
}

func main() {
	var (
		rockstarDir, treeDir, memoDir, boxDir string
	)

	flag.StringVar(&rockstarDir, "RockstarDir", "",
		"Directory containing Rockstar halo files.")
	flag.StringVar(&treeDir, "TreeDir", "",
		"Directory containing merger trees generated by consistent trees.")
	flag.StringVar(&memoDir, "MemoDir", "",
		"Directory where memoization will be performed.")
	flag.StringVar(&boxDir, "BoxDir", "",
		"Root 'Box' dir containing .gtet files.")

	flag.Parse()

	if !exists(rockstarDir) {
		log.Fatalf("Directory %s does not exist.", rockstarDir)
	} else if !exists(treeDir) {
		log.Fatalf("Directory %s does not exist.", treeDir)
	} else if !exists(boxDir) {
		log.Fatalf("Directory %s does not exist.", boxDir)
	}

	if !exists(memoDir) {
		err := os.MkdirAll(memoDir, os.ModeDir)
		if err != nil { log.Fatal(err.Error()) }
	}

	os.Setenv("GTET_ROCKSTAR_DIR", rockstarDir)
	os.Setenv("GTET_TREE_DIR", treeDir)
	os.Setenv("GTET_MEMO_DIR", memoDir)
	os.Setenv("GTET_BOX_DIR", boxDir)
}
